// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// 重要: 請用你的實際Firebase項目配置替換以下佔位符值。
/// 你可以從Firebase控制台獲取這些值:
/// 1. 訪問 https://console.firebase.google.com/
/// 2. 選擇你的項目
/// 3. 進入 "項目設置" -> "一般"
/// 4. 在 "我的應用" 部分下，找到你的iOS/Android應用
/// 5. 對於iOS，下載 GoogleService-Info.plist 並從中複製值
/// 6. 對於Android，下載 google-services.json 並從中複製值
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 注意: 請替換下面的值為你自己的配置!
  // 這些是佔位符值，不能直接使用!
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU2Mgn4ZWo62nceazuTTFoaZjbwb7Lz5M',
    appId: '1:351815823759:android:bfafd046fc4f17b5c09bfa',
    messagingSenderId: '351815823759',
    projectId: 'haroldsba-352a1',
    storageBucket: 'haroldsba-352a1.appspot.com',
  );

  // 注意: 請替換下面的值為你自己的配置!
  // 這些是佔位符值，不能直接使用!
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2Mgn4ZWo62nceazuTTFoaZjbwb7Lz5M',
    appId: '1:351815823759:ios:6acfd73cd1aa656ac09bfa',
    messagingSenderId: '351815823759',
    projectId: 'haroldsba-352a1',
    storageBucket: 'haroldsba-352a1.appspot.com',
    iosClientId:
        '351815823759-o5l2ei5d2i2b0p1asnldf4vbhv4qqm48.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbaaa',
  );
}
